### ISSUE TITLE
Determine final handler flow

### ISSUE THREAD

**Issue by theganyo** [30x/gozerian#6]
Questions:
1. Should we provide some abstraction for streaming and gathering the body like we did in edgemicro? Or just provide examples of how to gather the body? (Leaning toward examples to keep everything as close to idiomatic as possible.)
2. How should direct access to the ResponseWriter be handled? Should it always simply abort the pipeline at that point?

**Comment by theganyo** [comment]
Allow pipeline to select handlers to run dynamically?
Allow dynamically selecting a different response pipeline based on response data?

**Comment by mpnally** [comment]
I also like the idea of examples rather than framework. A good friend of
mine once told me that the definition of a framework is something that
everyone wants to build and nobody wants to use.

Martin

**Comment by theganyo** [comment]
Proposed resolution:
1. We'll go with examples as far as possible and keep the framework minimal. We'll add framework support where it's absolutely needed.
2. Any interaction with the ResponseWriter will be considered an abort of the current Pipeline and the Response will be written to the client as specified.
3. For now, the pipeline will just execute all passed handlers blindly. We may want to add the ability to select handlers in a Pipeline with some kind of conditional in the future, but this could also easily be done by writing a simple wrapper around any handlers or building the pipeline at the moment of the request.
4. Similar to #3, keep it simple and static for now.
